### PR TITLE
Updated Polish language

### PR DESCRIPTION
**Pull request by Daviteusz**
I just noticed after adding PR that there are changes in #1085 for Polish translation.
I use Weblate because it makes translation very easy, but unfortunately it adds many unnecessary lines.

I will add the new changes manually after merging mentioned PR.

### CODE REVIEW

**Comment by AdamVe** [comment]
Hi @Daviteusz, I have merged #1085 so you are welcome to rebase this PR and I will merge it in 👍🏻 Thanks!

**Comment by Daviteusz** [comment]
@AdamVe I modified the string layout to match the source file. Using weblate with ARB files was not a good idea.

It's ready to merge.

**Review by AdamVe — APPROVED** [review]
Tested on desktop and Android.

**Comment by AdamVe** [comment]
@Daviteusz thanks for your contribution!

**Pull request merged**
