### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by redDwarf03**
Hello

please find french translation

### CODE REVIEW

**Comment by redDwarf03** [comment]
relative to https://github.com/Yubico/yubioath-flutter/issues/783

**Comment by dainnilsson** [comment]
Thank you for your contribution!

We're not quite ready yet to merge support for additional languages. Many of the strings are currently being changed, and many are still hardcoded in the app and cannot be translated yet. We also have other things to consider with supporting strings of varying length in terms of UI layout. We are working on this and hope to be able to support it in the not-too-distant future!

**Comment by redDwarf03** [comment]
do not hesitate if you need ;)

**Comment by dainnilsson** [comment]
We have now completed the underlying changes we needed to be able to support additional languages. Unfortunately this work included a lot of restructuring in the string names, so this PR would need to be updated quite a bit before it can be merged.

**Comment by redDwarf03** [comment]
i will rebase the branch et rework my PR

**Comment by fdennis** [comment]
Closing this since another PR with French translation has been merged: #1125

**Pull request closed without merging**
