### PR TITLE
Updated the copyright year and author

### PR DESCRIPTION
**Pull request by Moyo-Made**

### CODE REVIEW

**Comment by dainnilsson** [comment]
Please explain what the purpose of this PR is.

**Comment by Moyo-Made** [comment]
> Please explain what the purpose of this PR is.

I added the copyright year and author that was missing in the LICENSE file

**Comment by dainnilsson** [comment]
Hi, thank you for your PR, but we are not going to use it as we are sure that we applied the Apache Version 2.0 license correctly in our repository: our source files apply the license through comments in the project source files. The LICENSE file is in the repository for easier identification within third party archives. The copyright holder and year you've used is also not correct.

**Comment by Moyo-Made** [comment]
> Hi, thank you for your PR, but we are not going to use it as we are sure that we applied the Apache Version 2.0 license correctly in our repository: our source files apply the license through comments in the project source files. The LICENSE file is in the repository for easier identification within third party archives. The copyright holder and year you've used is also not correct.

Okay.

**Pull request closed without merging**
